apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - app.yaml
  - rbac.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: external-dns-dynamic-ip
      app.kubernetes.io/instance: external-dns-dynamic-ip
