name: Build

on: push

env:
  KUBERNETES_VERSION: v1.33.1

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ghcr.io/gabe565/external-dns-dynamic-ip
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{version}},value=${{ env.KUBERNETES_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.KUBERNETES_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3.11.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
